[package]
name = "bpe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]
bench = false

[dependencies]
#daachorse = "1"
daachorse = { git = "https://github.com/aneubeck/daachorse.git", rev = "22f471532a25d90a320eae0902c759db2b8fe962" }
fnv = "1.0"
itertools = "0.12"
once_cell = "1"
rand = "0.8"
rmp-serde = "1"
serde = { version = "1", features = ["derive"] }
tiktoken-rs = "0.5"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "counting"
path = "benches/counting.rs"
harness = false
